global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # Rules will be managed by Grafana, not Prometheus
  # - "first_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 5s
    metrics_path: /metrics

  # Mock API service metrics for testing
  - job_name: 'mock-api'
    static_configs:
      - targets: ['node-exporter:9100']  # Using node-exporter as mock
    scrape_interval: 10s